// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Dku_uI6iFe398FCSgPDQp3ft1jAde0Q',
    appId: '1:592261910799:web:d11a355c074037ef4c6e7a',
    messagingSenderId: '592261910799',
    projectId: 'booksapp-18b76',
    authDomain: 'booksapp-18b76.firebaseapp.com',
    storageBucket: 'booksapp-18b76.firebasestorage.app',
    measurementId: 'G-JLBKHHSQ9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvVCir3nGZRsmJMCCJt4wLfSwkcDawjt8',
    appId: '1:592261910799:android:5d503535d4abc1764c6e7a',
    messagingSenderId: '592261910799',
    projectId: 'booksapp-18b76',
    storageBucket: 'booksapp-18b76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBomihii9PEjqXpNQWbdcVHL8G5VFiGKEQ',
    appId: '1:592261910799:ios:829887972cd0accf4c6e7a',
    messagingSenderId: '592261910799',
    projectId: 'booksapp-18b76',
    storageBucket: 'booksapp-18b76.firebasestorage.app',
    iosBundleId: 'com.example.booksapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBomihii9PEjqXpNQWbdcVHL8G5VFiGKEQ',
    appId: '1:592261910799:ios:829887972cd0accf4c6e7a',
    messagingSenderId: '592261910799',
    projectId: 'booksapp-18b76',
    storageBucket: 'booksapp-18b76.firebasestorage.app',
    iosBundleId: 'com.example.booksapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9Dku_uI6iFe398FCSgPDQp3ft1jAde0Q',
    appId: '1:592261910799:web:d1551cc71f848fb44c6e7a',
    messagingSenderId: '592261910799',
    projectId: 'booksapp-18b76',
    authDomain: 'booksapp-18b76.firebaseapp.com',
    storageBucket: 'booksapp-18b76.firebasestorage.app',
    measurementId: 'G-000KJM4HEY',
  );
}
